// Generated by CoffeeScript 1.6.3
(function() {
  var User, checkBasicProfile, crud, getUserAttributes, utils;

  utils = require('../lib/tools');

  crud = require('../lib/crud');

  User = crud.User;

  checkBasicProfile = function(req) {
    var userData;
    if (req.loggedIn) {
      userData = req.user;
      if (!userData.completedBasicProfile) {
        res.redirect('/');
      }
    }
  };

  getUserAttributes = function(usrData) {
    var renderObj;
    renderObj = {};
    renderObj.title = usrData.name + ' | flambé';
    renderObj.profileName = usrData.name;
    renderObj.profileUserName = usrData.userName;
    renderObj.profileDisplayName = usrData.displayName;
    renderObj.profileAvatar = usrData.photoUrl;
    renderObj.profileStatus = usrData.status;
    if (usrData.social.twitter) {
      renderObj.profileTwitter = usrData.social.twitter.url;
    }
    if (usrData.social.facebook) {
      renderObj.profileFacebook = usrData.social.facebook.url;
    }
    if (usrData.social.linkedin) {
      renderObj.profileLinkedIn = usrData.social.linkedin.url;
    }
    if (usrData.website) {
      renderObj.profileWebsite = usrData.website.url;
    }
    renderObj.lastPostDate = utils.fromNow('October 4, 2013');
    return renderObj;
  };

  exports.index = function(req, res) {
    checkBasicProfile(req, res);
    return User.readOne({
      userName: req.params.username
    }, function(err, rslt) {
      if (err) {
        res(err);
      }
      if (rslt) {
        return res.render('profile', getUserAttributes(rslt));
      } else {
        return res.send('Error page: chef not found. Go <a href="/">home</a>.');
      }
    });
  };

  exports.byId = function(req, res) {
    checkBasicProfile(req, res);
    return User.readById(req.params.id, function(err, rslt) {
      if (err) {
        res(err);
      }
      if (rslt) {
        return res.render('profile', getUserAttributes(rslt));
      } else {
        return res.send('Error page: chef not found. Go <a href="/">home</a>.');
      }
    });
  };

}).call(this);
