// Generated by CoffeeScript 1.6.3
(function() {
  var User, crud;

  crud = require('../lib/crud');

  User = crud.User;

  exports.users = function(req, res) {
    return User.read({}, function(err, rslts) {
      if (err) {
        res.jsonp(err);
      }
      res.jsonp(rslts);
      return next();
    });
  };

  exports.user = function(req, res) {
    return User.readById(req.params.id, function(err, rslts) {
      if (err) {
        res.jsonp(err);
      }
      return res.jsonp(rslts);
    });
  };

  exports.userByUserName = function(req, res) {
    return User.readOne({
      userName: req.params.username
    }, function(err, rslts) {
      if (err) {
        res.jsonp(err);
      }
      return res.jsonp(rslts);
    });
  };

  exports.checkUserName = function(req, res) {
    return User.suggestUserName(req.params.username, function(suggestion) {
      return res.jsonp(suggestion);
    });
  };

  exports.checkEmailExists = function(req, res) {
    return User.checkExistingEmail(req.params.email, function(suggestion) {
      return res.jsonp(suggestion);
    });
  };

}).call(this);
