// Generated by CoffeeScript 1.6.3
(function() {
  var User, crud, keys, util;

  util = require('util');

  keys = require('./keys');

  crud = require('./crud');

  User = crud.User;

  module.exports = {
    init: function(everyauth) {
      everyauth.everymodule.findUserById(function(id, cb) {
        return User.readById(id, function(err, rslt) {
          return cb(err, rslt);
        });
      });
      everyauth.everymodule.userPkey('_id');
      everyauth.twitter.consumerKey(keys.twitter.consumerKey);
      everyauth.twitter.consumerSecret(keys.twitter.consumerSecret);
      everyauth.twitter.findOrCreateUser(function(session, accessToken, accessTokenSecret, data) {
        var promise;
        promise = this.Promise();
        User.findOrCreateUserByTwitterData(data, promise);
        return promise;
      });
      everyauth.twitter.redirectPath('/welcome');
      everyauth.facebook.appId(keys.facebook.appId);
      everyauth.facebook.appSecret(keys.facebook.appSecret);
      everyauth.facebook.findOrCreateUser(function(session, accessToken, accessTokExtra, data) {
        var promise;
        promise = this.Promise();
        User.findOrCreateUserByFacebookData(data, promise);
        return promise;
      });
      everyauth.facebook.redirectPath('/welcome');
      everyauth.linkedin.consumerKey(keys.linkedin.consumerKey);
      everyauth.linkedin.consumerSecret(keys.linkedin.consumerSecret);
      everyauth.linkedin.findOrCreateUser(function(session, accessToken, accessTokenSecret, data) {
        var promise;
        promise = this.Promise();
        User.findOrCreateUserByLinkedinData(data, promise);
        return promise;
      });
      return everyauth.linkedin.redirectPath('/welcome');
    }
  };

}).call(this);
