// Generated by CoffeeScript 1.6.3
(function() {
  module.exports = {
    twitter: {
      consumerKey: 'dnFdNTKxjbWAnpZDKvEHHw',
      consumerSecret: 'PA5vzyXgLCayZI0XvDoGWpFnMKaLGixEsJmj3qZjQk'
    },
    facebook: {
      app_id: '442729819170932',
      app_secret: '37f03f5ef6a943f6e32b683bf8aa4269'
    },
    linkedin: {
      api_key: 'k3jgw1b47iod',
      secret_key: 'J5tR02tUZUuDxyDm',
      oauth_user_token: 'ea9f66c0-e970-492b-8e8e-d46863785aa8',
      oauth_user_secret: 'cfdd3d80-68f9-4ecd-a79b-4b06e76066bd'
    }
  };

}).call(this);
