// Generated by CoffeeScript 1.6.3
(function() {
  var moment;

  moment = require('moment');

  module.exports = {
    echo: function(data) {
      return data;
    },
    shortDate: function(date) {
      return moment(date).format('MM.DD.YYYY');
    },
    fromNow: function(date) {
      return moment(date).fromNow();
    }
  };

}).call(this);
